/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuyerLead {
  'id' : bigint,
  'buyerEmail' : string,
  'createdAt' : Time,
  'buyerPhone' : string,
  'propertyId' : bigint,
  'message' : string,
  'buyerName' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Property {
  'id' : bigint,
  'status' : PropertyStatus,
  'title' : string,
  'photoUrls' : Array<string>,
  'propertyType' : string,
  'bedrooms' : bigint,
  'area' : bigint,
  'city' : string,
  'submittedAt' : Time,
  'description' : string,
  'sellerInfo' : SellerInfo,
  'isFeatured' : boolean,
  'price' : bigint,
  'location' : string,
}
export type PropertyStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface SellerInfo {
  'paymentStatus' : PaymentStatus,
  'sellerPhone' : [] | [string],
  'sellerName' : string,
  'paymentRef' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'filterPropertiesByCity' : ActorMethod<[string], Array<Property>>,
  'getAllBuyerLeads' : ActorMethod<[], Array<BuyerLead>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getSellerPhone' : ActorMethod<[bigint], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listApprovedProperties' : ActorMethod<[], Array<Property>>,
  'recordPayment' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBuyerInquiry' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'submitProperty' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      string,
      Array<string>,
      string,
      string,
    ],
    undefined
  >,
  'toggleFeatured' : ActorMethod<[bigint], undefined>,
  'updatePropertyStatus' : ActorMethod<[bigint, PropertyStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];